# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "interface_consumer"
version = "0.1.0"
kind = "executable"
entry = "src/main.rz"

[dependencies]
interface_dependency = "../interface-dependency"
