# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

function(materialize_compiler_source SOURCE_ROOT OUTPUT_PATH)
  set(order_path "${SOURCE_ROOT}/compiler/host-source-order.txt")
  if(NOT EXISTS "${order_path}")
    message(FATAL_ERROR "Compiler source order missing: ${order_path}")
  endif()
  file(STRINGS "${order_path}" ordered_sources)
  file(WRITE "${OUTPUT_PATH}" "")
  set(count 0)
  foreach(relative IN LISTS ordered_sources)
    string(STRIP "${relative}" relative)
    if(relative STREQUAL "" OR relative MATCHES "^#")
      continue()
    endif()
    set(source "${SOURCE_ROOT}/compiler/${relative}")
    if(NOT EXISTS "${source}")
      message(FATAL_ERROR "Compiler source-order entry missing: ${source}")
    endif()
    file(READ "${source}" content)
    file(APPEND "${OUTPUT_PATH}" "${content}")
    string(LENGTH "${content}" content_length)
    if(content_length GREATER 0)
      math(EXPR last_index "${content_length} - 1")
      string(SUBSTRING "${content}" ${last_index} 1 final_char)
      if(NOT final_char STREQUAL "\n")
        file(APPEND "${OUTPUT_PATH}" "\n")
      endif()
    endif()
    math(EXPR count "${count} + 1")
  endforeach()
  if(count LESS 2)
    message(FATAL_ERROR "Expected modular compiler compiler source set, found ${count} module(s)")
  endif()
endfunction()
