# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED PROJECT_ROOT OR NOT EXISTS "${PROJECT_ROOT}/compiler/src/main.rz")
  message(FATAL_ERROR "Canonical compiler compiler entrypoint is missing: ${PROJECT_ROOT}/compiler/src/main.rz")
endif()
if(NOT EXISTS "${PROJECT_ROOT}/compiler/host-source-order.txt")
  message(FATAL_ERROR "Canonical compiler compiler source order is missing: ${PROJECT_ROOT}/compiler/host-source-order.txt")
endif()
file(GLOB_RECURSE compiler_sources RELATIVE "${PROJECT_ROOT}/compiler" "${PROJECT_ROOT}/compiler/src/*.rz")
list(SORT compiler_sources)
file(STRINGS "${PROJECT_ROOT}/compiler/host-source-order.txt" source_order)
list(FILTER source_order EXCLUDE REGEX "^[ \t]*($|#)")
if(NOT source_order)
  message(FATAL_ERROR "compiler/host-source-order.txt is empty")
endif()
list(GET source_order -1 entry)
if(NOT entry STREQUAL "src/main.rz")
  message(FATAL_ERROR "compiler/host-source-order.txt must end with src/main.rz")
endif()
list(SORT source_order)
if(NOT compiler_sources STREQUAL source_order)
  message(FATAL_ERROR "compiler/host-source-order.txt must cover compiler/src/*.rz exactly")
endif()
foreach(forbidden IN ITEMS
    "${PROJECT_ROOT}/frontend.rz"
    "${PROJECT_ROOT}/compiler/frontend.rz"
    "${PROJECT_ROOT}/src/bootstrap/seed/frontend.rz"
    "${PROJECT_ROOT}/src/bootstrap/seed/compiler/frontend.rz"
    "${PROJECT_ROOT}/src/bootstrap/seed/src/main.rz")
  if(EXISTS "${forbidden}")
    message(FATAL_ERROR "Redundant compiler compiler source must not be committed: ${forbidden}")
  endif()
endforeach()
message(STATUS "Canonical modular compiler compiler source layout: PASS")

if(NOT DEFINED BOOTSTRAP_SCRIPT OR NOT EXISTS "${BOOTSTRAP_SCRIPT}")
  message(FATAL_ERROR "Bootstrap driver is missing: ${BOOTSTRAP_SCRIPT}")
endif()
file(READ "${BOOTSTRAP_SCRIPT}" bootstrap_driver)
string(FIND "${bootstrap_driver}" [['stage-input.txt', "stage$Stage.fir"]] source_list_call)
if(source_list_call EQUAL -1)
  message(FATAL_ERROR "Recursive bootstrap must invoke generated stages through stage-input.txt, not raz.toml project loading.")
endif()
string(FIND "${bootstrap_driver}" "--forge-structured-only" structured_backend_call)
if(structured_backend_call EQUAL -1)
  message(FATAL_ERROR "Recursive bootstrap must use the structured Forge backend for compiler-sized fixed-point stages.")
endif()
string(FIND "${bootstrap_driver}" "host-source-order.txt" source_order_contract)
if(source_order_contract EQUAL -1)
  message(FATAL_ERROR "Recursive bootstrap must consume compiler/host-source-order.txt.")
endif()
string(FIND "${bootstrap_driver}" "src/main.rz'" entry_last_contract)
if(entry_last_contract EQUAL -1)
  message(FATAL_ERROR "Recursive bootstrap must preserve src/main.rz as the final source-list entry.")
endif()
message(STATUS "Recursive compiler ordered source-list transport: PASS")

set(native_project_loader "${PROJECT_ROOT}/src/bootstrap/compiler/project/project.cpp")
set(raz_project_loader "${PROJECT_ROOT}/compiler/src/driver/project.rz")
foreach(loader IN ITEMS "${native_project_loader}" "${raz_project_loader}")
  if(NOT EXISTS "${loader}")
    message(FATAL_ERROR "Project loader missing: ${loader}")
  endif()
  file(READ "${loader}" loader_text)
  string(FIND "${loader_text}" "source-order.txt" source_order_support)
  if(source_order_support EQUAL -1)
    message(FATAL_ERROR "Project loader must honor optional source-order.txt: ${loader}")
  endif()
endforeach()
message(STATUS "Explicit package source-order contract: PASS")
