# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED RAZ_EXE OR NOT DEFINED FIXTURE_ROOT)
  message(FATAL_ERROR "RAZ_EXE and FIXTURE_ROOT are required")
endif()
foreach(kind IN ITEMS static shared executable)
  set(project "${FIXTURE_ROOT}/native-artifact-${kind}")
  execute_process(COMMAND "${RAZ_EXE}" build "${project}" --target host --profile release --force
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${kind} native build failed:\n${output}\n${error}")
  endif()
endforeach()
execute_process(COMMAND "${RAZ_EXE}" build "${FIXTURE_ROOT}/native-artifact-static" --target host --profile release --verbose
  RESULT_VARIABLE static_fresh_result OUTPUT_VARIABLE static_fresh_output ERROR_VARIABLE static_fresh_error)
if(NOT static_fresh_result EQUAL 0)
  message(FATAL_ERROR "static native fresh build failed:\n${static_fresh_output}\n${static_fresh_error}")
endif()
if(NOT static_fresh_output MATCHES "Fresh[ ]+native_artifact_static native archive")
  message(FATAL_ERROR "static native archive was unnecessarily regenerated:\n${static_fresh_output}")
endif()
if(WIN32)
  set(static_artifact "${FIXTURE_ROOT}/native-artifact-static/target/host/release/native_artifact_static.lib")
  set(shared_artifact "${FIXTURE_ROOT}/native-artifact-shared/target/host/release/native_artifact_shared.dll")
  set(exe_artifact "${FIXTURE_ROOT}/native-artifact-executable/target/host/release/native_artifact_executable.exe")
else()
  set(static_artifact "${FIXTURE_ROOT}/native-artifact-static/target/host/release/libnative_artifact_static.a")
  set(shared_artifact "${FIXTURE_ROOT}/native-artifact-shared/target/host/release/libnative_artifact_shared.so")
  set(exe_artifact "${FIXTURE_ROOT}/native-artifact-executable/target/host/release/native_artifact_executable")
endif()
foreach(path IN ITEMS "${static_artifact}" "${shared_artifact}" "${exe_artifact}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "missing native artifact ${path}")
  endif()
  file(SIZE "${path}" size)
  if(size LESS 64)
    message(FATAL_ERROR "native artifact is unexpectedly small: ${path}")
  endif()
endforeach()
execute_process(COMMAND "${exe_artifact}" RESULT_VARIABLE run_result)
if(NOT run_result EQUAL 0)
  message(FATAL_ERROR "native executable failed with ${run_result}")
endif()
