# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED RAZ_EXE OR NOT DEFINED SOURCE OR NOT DEFINED WORK)
  message(FATAL_ERROR "missing RAZ_EXE, SOURCE, or WORK")
endif()
file(REMOVE_RECURSE "${WORK}")
file(COPY "${SOURCE}/" DESTINATION "${WORK}")

function(run_raz)
  execute_process(COMMAND "${RAZ_EXE}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "raz ${ARGN} failed (${result})\n${output}\n${error}")
  endif()
endfunction()

run_raz(fmt "${WORK}")
file(GLOB_RECURSE formatted_sources "${WORK}/*.rz")
list(SORT formatted_sources)
set(format_hash_1 "")
foreach(source IN LISTS formatted_sources)
  file(SHA256 "${source}" hash)
  string(APPEND format_hash_1 "${source}:${hash}\n")
endforeach()
run_raz(fmt "${WORK}")
set(format_hash_2 "")
foreach(source IN LISTS formatted_sources)
  file(SHA256 "${source}" hash)
  string(APPEND format_hash_2 "${source}:${hash}\n")
endforeach()
if(NOT format_hash_1 STREQUAL format_hash_2)
  message(FATAL_ERROR "formatter is not idempotent")
endif()
run_raz(fmt "${WORK}" --check)

run_raz(lock "${WORK}")
file(SHA256 "${WORK}/raz.lock" lock_1)
run_raz(lock "${WORK}")
file(SHA256 "${WORK}/raz.lock" lock_2)
if(NOT lock_1 STREQUAL lock_2)
  message(FATAL_ERROR "lockfile is not reproducible")
endif()
run_raz(verify "${WORK}")

run_raz(doc "${WORK}")
file(SHA256 "${WORK}/target/doc/index.html" doc_1)
run_raz(doc "${WORK}")
file(SHA256 "${WORK}/target/doc/index.html" doc_2)
if(NOT doc_1 STREQUAL doc_2)
  message(FATAL_ERROR "documentation output is not reproducible")
endif()

run_raz(spec "${WORK}")
if(NOT EXISTS "${WORK}/target/spec/spec.json")
  message(FATAL_ERROR "specification manifest missing")
endif()
file(READ "${WORK}/target/spec/spec.json" spec)
if(NOT spec MATCHES "raz-language-spec-v1" OR NOT spec MATCHES "languageVersion")
  message(FATAL_ERROR "specification manifest invalid")
endif()

run_raz(sbom "${WORK}")
file(SHA256 "${WORK}/target/security/sbom.json" sbom_1)
run_raz(sbom "${WORK}")
file(SHA256 "${WORK}/target/security/sbom.json" sbom_2)
if(NOT sbom_1 STREQUAL sbom_2)
  message(FATAL_ERROR "SBOM is not reproducible")
endif()
run_raz(audit "${WORK}")
run_raz(fuzz "${WORK}" --cases 32 --seed 987654321)
file(SHA256 "${WORK}/target/fuzz/FUZZ-RESULT.txt" fuzz_1)
run_raz(fuzz "${WORK}" --cases 32 --seed 987654321)
file(SHA256 "${WORK}/target/fuzz/FUZZ-RESULT.txt" fuzz_2)
if(NOT fuzz_1 STREQUAL fuzz_2)
  message(FATAL_ERROR "deterministic fuzz result changed for identical seed")
endif()

message(STATUS "Milestone C toolchain qualification passed")
