# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "std"
version = "1.0.0"
kind = "static-library"
entry = "io/io.rz"

[dependencies]
alloc = "../alloc"
core = "../core"

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 3
debug = false
incremental = true
