# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "raz-query"
version = "1.0.0"
kind = "static-library"
source = "src"
entry = "src/lib.rz"

[dependencies]

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 2
debug = false
incremental = true
