# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "raz-driver"
version = "1.0.0"
kind = "static-library"
source = "src"
entry = "src/lib.rz"

[dependencies]
borrowck = "../raz_borrowck"
forge = "../raz_codegen_forge"
llvm = "../raz_codegen_llvm"
wasm = "../raz_codegen_wasm"
rxe = "../raz_codegen_rxe"
web = "../raz_codegen_web"
frontend = "../raz_parser"
hir = "../raz_hir"
mir = "../raz_mir"
mir_opt = "../raz_mir_opt"

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 2
debug = false
incremental = true
