# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED RAZ OR NOT DEFINED WORK)
  message(FATAL_ERROR "missing test arguments")
endif()
file(MAKE_DIRECTORY "${WORK}")
function(frame name json)
  string(LENGTH "${json}" length)
  set(${name} "Content-Length: ${length}\r\n\r\n${json}" PARENT_SCOPE)
endfunction()
set(initialize "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}")
set(open "{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\",\"text\":\"fn main() -> i64 {\\n\\treturn 0;  \\n\"}}}")
set(format "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"textDocument/formatting\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(hover "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"position\":{\"line\":0,\"character\":2}}}")
set(completion "{\"jsonrpc\":\"2.0\",\"id\":4,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"position\":{\"line\":0,\"character\":2}}}")
set(symbols "{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"textDocument/documentSymbol\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(definition "{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"textDocument/definition\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"position\":{\"line\":1,\"character\":3}}}")
set(workspace "{\"jsonrpc\":\"2.0\",\"id\":7,\"method\":\"workspace/symbol\",\"params\":{\"query\":\"main\"}}")
set(references "{\"jsonrpc\":\"2.0\",\"id\":8,\"method\":\"textDocument/references\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"name\":\"main\"}}")
set(rename "{\"jsonrpc\":\"2.0\",\"id\":9,\"method\":\"textDocument/rename\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"name\":\"main\",\"newName\":\"entry\"}}")
set(signature "{\"jsonrpc\":\"2.0\",\"id\":10,\"method\":\"textDocument/signatureHelp\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"position\":{\"line\":0,\"character\":5}}}")
set(tokens "{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"textDocument/semanticTokens/full\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(code_action "{\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"textDocument/codeAction\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(inlay "{\"jsonrpc\":\"2.0\",\"id\":13,\"method\":\"textDocument/inlayHint\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(folding "{\"jsonrpc\":\"2.0\",\"id\":14,\"method\":\"textDocument/foldingRange\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(highlight "{\"jsonrpc\":\"2.0\",\"id\":15,\"method\":\"textDocument/documentHighlight\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"},\"name\":\"main\"}}")
set(selection "{\"jsonrpc\":\"2.0\",\"id\":16,\"method\":\"textDocument/selectionRange\",\"params\":{\"textDocument\":{\"uri\":\"file:///test.rz\"}}}")
set(shutdown "{\"jsonrpc\":\"2.0\",\"id\":17,\"method\":\"shutdown\",\"params\":null}")
set(exit_message "{\"jsonrpc\":\"2.0\",\"method\":\"exit\"}")
frame(f1 "${initialize}")
frame(f2 "${open}")
frame(f3 "${format}")
frame(f4 "${hover}")
frame(f5 "${completion}")
frame(f6 "${symbols}")
frame(f7 "${definition}")
frame(f8 "${workspace}")
frame(f9 "${references}")
frame(f10 "${rename}")
frame(f11 "${signature}")
frame(f12 "${tokens}")
frame(f13 "${code_action}")
frame(f14 "${inlay}")
frame(f15 "${folding}")
frame(f16 "${highlight}")
frame(f17 "${selection}")
frame(f18 "${shutdown}")
frame(f19 "${exit_message}")
file(WRITE "${WORK}/input.txt" "${f1}${f2}${f3}${f4}${f5}${f6}${f7}${f8}${f9}${f10}${f11}${f12}${f13}${f14}${f15}${f16}${f17}${f18}${f19}")
execute_process(COMMAND "${RAZ}" lsp INPUT_FILE "${WORK}/input.txt" OUTPUT_VARIABLE output RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT output MATCHES "documentFormattingProvider" OR NOT output MATCHES "hoverProvider" OR NOT output MATCHES "completionProvider" OR NOT output MATCHES "documentSymbolProvider" OR NOT output MATCHES "referencesProvider" OR NOT output MATCHES "renameProvider" OR NOT output MATCHES "workspaceSymbolProvider" OR NOT output MATCHES "signatureHelpProvider" OR NOT output MATCHES "semanticTokensProvider" OR NOT output MATCHES "codeActionProvider" OR NOT output MATCHES "inlayHintProvider" OR NOT output MATCHES "foldingRangeProvider" OR NOT output MATCHES "documentHighlightProvider" OR NOT output MATCHES "selectionRangeProvider")
  message(FATAL_ERROR "LSP handshake failed: ${output}")
endif()
if(NOT output MATCHES "publishDiagnostics" OR NOT output MATCHES "L002" OR NOT output MATCHES "D1002")
  message(FATAL_ERROR "LSP diagnostics missing: ${output}")
endif()
if(NOT output MATCHES "newText" OR NOT output MATCHES "Raz function" OR NOT output MATCHES "entry" OR NOT output MATCHES "\\\"result\\\":null")
  message(FATAL_ERROR "LSP semantic operations failed: ${output}")
endif()
