# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED RAZ OR NOT DEFINED SOURCE OR NOT DEFINED WORK OR NOT DEFINED MODE)
  message(FATAL_ERROR "missing test arguments")
endif()
file(REMOVE_RECURSE "${WORK}")
file(COPY "${SOURCE}/" DESTINATION "${WORK}")
if(MODE STREQUAL "fmt")
  execute_process(COMMAND "${RAZ}" fmt "${WORK}" --check RESULT_VARIABLE before)
  if(before EQUAL 0)
    message(FATAL_ERROR "format check unexpectedly passed before formatting")
  endif()
  execute_process(COMMAND "${RAZ}" fmt "${WORK}" RESULT_VARIABLE format_result)
  if(NOT format_result EQUAL 0)
    message(FATAL_ERROR "format command failed")
  endif()
  execute_process(COMMAND "${RAZ}" fmt "${WORK}" --check RESULT_VARIABLE after)
  if(NOT after EQUAL 0)
    message(FATAL_ERROR "format check failed after formatting")
  endif()
elseif(MODE STREQUAL "lint")
  execute_process(COMMAND "${RAZ}" lint "${WORK}" --deny-warnings RESULT_VARIABLE result)
  if(result EQUAL 0)
    message(FATAL_ERROR "lint unexpectedly accepted formatting warnings")
  endif()
elseif(MODE STREQUAL "lock")
  file(REMOVE "${WORK}/raz.lock")
  execute_process(COMMAND "${RAZ}" lock "${WORK}" RESULT_VARIABLE result)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/raz.lock")
    message(FATAL_ERROR "lock command failed")
  endif()
  file(READ "${WORK}/raz.lock" lockfile)
  if(NOT lockfile MATCHES "version = 1" OR NOT lockfile MATCHES "tooling-package")
    message(FATAL_ERROR "lockfile contents invalid")
  endif()
elseif(MODE STREQUAL "verify")
  execute_process(COMMAND "${RAZ}" lock "${WORK}" RESULT_VARIABLE lock_result)
  execute_process(COMMAND "${RAZ}" verify "${WORK}" RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output)
  if(NOT lock_result EQUAL 0 OR NOT verify_result EQUAL 0 OR NOT verify_output MATCHES "Verified tooling-package")
    message(FATAL_ERROR "verify command failed: ${verify_output}")
  endif()
  file(APPEND "${WORK}/raz.lock" "# modified\n")
  execute_process(COMMAND "${RAZ}" verify "${WORK}" RESULT_VARIABLE stale_result)
  if(stale_result EQUAL 0)
    message(FATAL_ERROR "verify accepted a modified lockfile")
  endif()
elseif(MODE STREQUAL "bench")
  execute_process(COMMAND "${RAZ}" bench "${WORK}" --iterations 2 RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT output MATCHES "bench smoke: median")
    message(FATAL_ERROR "benchmark command failed: ${output}")
  endif()
elseif(MODE STREQUAL "coverage")
  execute_process(COMMAND "${RAZ}" coverage "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/coverage/coverage.json" OR NOT EXISTS "${WORK}/target/coverage/index.html")
    message(FATAL_ERROR "coverage command failed: ${output}")
  endif()
  file(READ "${WORK}/target/coverage/coverage.json" report)
  if(NOT report MATCHES "raz-symbol-coverage-v1" OR NOT report MATCHES "tooling-package")
    message(FATAL_ERROR "coverage report invalid")
  endif()
elseif(MODE STREQUAL "fuzz")
  execute_process(COMMAND "${RAZ}" fuzz "${WORK}" --cases 24 --seed 12345 RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/fuzz/FUZZ-RESULT.txt" OR NOT output MATCHES "Fuzzed 24 deterministic compiler cases")
    message(FATAL_ERROR "fuzz command failed: ${output}")
  endif()
elseif(MODE STREQUAL "profile")
  execute_process(COMMAND "${RAZ}" profile "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/profile/compile-profile.json" OR NOT EXISTS "${WORK}/target/profile/compile-profile.txt" OR NOT output MATCHES "Profiled")
    message(FATAL_ERROR "profile command failed: ${output}")
  endif()
  file(READ "${WORK}/target/profile/compile-profile.json" profile)
  if(NOT profile MATCHES "raz-compile-profile-v1" OR NOT profile MATCHES "tooling-package")
    message(FATAL_ERROR "compile profile contents invalid")
  endif()
elseif(MODE STREQUAL "publish")
  set(registry "${WORK}/local-registry")
  execute_process(COMMAND "${RAZ}" publish "${WORK}" --registry "${registry}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${registry}/tooling-package/0.1.0/tooling-package-0.1.0.zip" OR NOT EXISTS "${registry}/tooling-package/0.1.0/package.json")
    message(FATAL_ERROR "publish command failed: ${output}")
  endif()
  file(READ "${registry}/tooling-package/0.1.0/package.json" metadata)
  if(NOT metadata MATCHES "raz-registry-package-v1" OR NOT metadata MATCHES "checksum")
    message(FATAL_ERROR "publish metadata invalid")
  endif()
elseif(MODE STREQUAL "package")
  execute_process(COMMAND "${RAZ}" package "${WORK}" RESULT_VARIABLE result)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/package/tooling-package-0.1.0.zip")
    message(FATAL_ERROR "package command failed")
  endif()
elseif(MODE STREQUAL "install")
  set(prefix "${WORK}/installed")
  execute_process(COMMAND "${RAZ}" install "${WORK}" --prefix "${prefix}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${prefix}/packages/tooling-package/0.1.0/INSTALL-RECEIPT.txt")
    message(FATAL_ERROR "install command failed: ${output}")
  endif()
  execute_process(COMMAND "${RAZ}" uninstall "${WORK}" --prefix "${prefix}" RESULT_VARIABLE remove_result)
  if(NOT remove_result EQUAL 0 OR EXISTS "${prefix}/packages/tooling-package/0.1.0")
    message(FATAL_ERROR "uninstall command failed")
  endif()
elseif(MODE STREQUAL "sbom")
  execute_process(COMMAND "${RAZ}" sbom "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/security/sbom.json" OR NOT output MATCHES "Generated SBOM")
    message(FATAL_ERROR "sbom command failed: ${output}")
  endif()
  file(READ "${WORK}/target/security/sbom.json" sbom)
  if(NOT sbom MATCHES "raz-sbom-v1" OR NOT sbom MATCHES "tooling-package")
    message(FATAL_ERROR "sbom contents invalid")
  endif()
elseif(MODE STREQUAL "audit")
  execute_process(COMMAND "${RAZ}" audit "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT output MATCHES "Audit passed")
    message(FATAL_ERROR "audit command failed: ${output}")
  endif()
elseif(MODE STREQUAL "testreport")
  execute_process(COMMAND "${RAZ}" test "${WORK}" --list RESULT_VARIABLE list_result OUTPUT_VARIABLE list_output)
  if(NOT list_result EQUAL 0 OR NOT list_output MATCHES "tests/smoke.rz")
    message(FATAL_ERROR "test listing failed: ${list_output}")
  endif()
  execute_process(COMMAND "${RAZ}" test "${WORK}" --report "${WORK}/custom-results.json" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/test-results/results.json" OR NOT EXISTS "${WORK}/target/test-results/junit.xml" OR NOT EXISTS "${WORK}/custom-results.json")
    message(FATAL_ERROR "structured test reporting failed: ${output}")
  endif()
elseif(MODE STREQUAL "graph")
  execute_process(COMMAND "${RAZ}" graph "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/metadata/dependency-graph.json" OR NOT EXISTS "${WORK}/target/metadata/dependency-graph.dot")
    message(FATAL_ERROR "dependency graph command failed: ${output}")
  endif()
  file(READ "${WORK}/target/metadata/dependency-graph.json" graph)
  if(NOT graph MATCHES "raz-dependency-graph-v1" OR NOT graph MATCHES "tooling-package")
    message(FATAL_ERROR "dependency graph contents invalid")
  endif()
elseif(MODE STREQUAL "doctor")
  execute_process(COMMAND "${RAZ}" doctor "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/target/doctor/doctor.json" OR NOT output MATCHES "Doctor passed")
    message(FATAL_ERROR "doctor command failed: ${output}")
  endif()
  file(READ "${WORK}/target/doctor/doctor.json" report)
  if(NOT report MATCHES "raz-doctor-v1" OR NOT report MATCHES "tooling-package")
    message(FATAL_ERROR "doctor report invalid")
  endif()
elseif(MODE STREQUAL "cache")
  execute_process(COMMAND "${RAZ}" build "${WORK}" RESULT_VARIABLE build_result)
  execute_process(COMMAND "${RAZ}" cache "${WORK}" RESULT_VARIABLE inspect_result OUTPUT_VARIABLE inspect_output)
  if(NOT build_result EQUAL 0 OR NOT inspect_result EQUAL 0 OR NOT inspect_output MATCHES "byte")
    message(FATAL_ERROR "cache inspection failed: ${inspect_output}")
  endif()
  execute_process(COMMAND "${RAZ}" cache "${WORK}" --prune RESULT_VARIABLE prune_result OUTPUT_VARIABLE prune_output)
  if(NOT prune_result EQUAL 0 OR EXISTS "${WORK}/.raz/cache" OR NOT prune_output MATCHES "Pruned")
    message(FATAL_ERROR "cache pruning failed: ${prune_output}")
  endif()
elseif(MODE STREQUAL "doc")
  execute_process(COMMAND "${RAZ}" doc "${WORK}" RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "doc command failed")
  endif()
  if(NOT EXISTS "${WORK}/target/doc/index.html" OR NOT EXISTS "${WORK}/target/doc/main.html")
    message(FATAL_ERROR "documentation output missing")
  endif()
  file(READ "${WORK}/target/doc/main.html" page)
  if(NOT page MATCHES "Program entry point")
    message(FATAL_ERROR "documentation comment missing")
  endif()
endif()
