#!/usr/bin/env python3
# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import os
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[2]


def run(cmd: list[str], cwd: Path, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--raz', required=True)
    ap.add_argument('--work-root', required=True)
    args = ap.parse_args()

    raz = Path(args.raz).resolve()
    work = Path(args.work_root).resolve()
    if work.exists():
        shutil.rmtree(work)
    project = work / 'bundle-hardening'
    shutil.copytree(ROOT / 'tests' / 'examples' / 'web' / 'reactive', project)

    manifest = project / 'raz.toml'
    manifest.write_text(manifest.read_text(encoding='utf-8') + '\njavascript = "custom.js"\n', encoding='utf-8')
    user_js = "// user spacing must survive release compaction\nconst   userSpacing   =   'kept';\nglobalThis.__razUserSpacing = userSpacing;\n"
    (project / 'custom.js').write_text(user_js, encoding='utf-8')

    env = os.environ.copy()
    env['RAZ_HOME'] = str(ROOT)
    runtime = ROOT / 'build' / 'release' / 'src' / 'runtime' / 'libraz_runtime.a'
    if runtime.is_file():
        env['RAZ_RUNTIME_LIBRARY'] = str(runtime)

    debug = run([str(raz), 'build', 'raz.toml'], project, env)
    if debug.returncode != 0:
        print(debug.stdout)
        return 1
    debug_js_path = project / 'dist' / 'assets' / 'app.js'
    if not debug_js_path.is_file():
        print('web-bundle-hardening: debug app.js missing')
        return 1
    debug_js = debug_js_path.read_text(encoding='utf-8')
    # Release asset fingerprinting replaces the debug dist tree, so validate
    # the stable-name debug loader before the release build removes app.js.
    checked = subprocess.run(['node', '--check', str(debug_js_path)], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if checked.returncode != 0:
        print(checked.stdout)
        return 1

    release = run([str(raz), 'build', '--release', 'raz.toml'], project, env)
    if release.returncode != 0:
        print(release.stdout)
        return 1
    release_candidates = sorted((project / 'dist' / 'assets').glob('app.*.js'))
    if len(release_candidates) != 1:
        print('web-bundle-hardening: release fingerprinted app.js missing')
        return 1
    release_js_path = release_candidates[0]
    release_js = release_js_path.read_text(encoding='utf-8')

    checks = {
        'debug loader remains readable': '// Generated by the Raz web backend.' in debug_js and debug_js.count('\n') > 80,
        'release strips generated comments/newlines': '// Generated by the Raz web backend.' not in release_js and release_js.count('\n') <= user_js.count('\n') + 2,
        'release glue is smaller': len(release_js) + 250 < len(debug_js),
        'streaming wasm instantiation': 'WebAssembly.instantiateStreaming(fetch(wasmUrl), imports)' in debug_js and 'WebAssembly.instantiateStreaming(fetch(wasmUrl), imports)' in release_js,
        'compatibility wasm fallback': 'WebAssembly.instantiate(bytes, imports)' in release_js,
        'single delegated click listener': debug_js.count("root.addEventListener('click'") == 1 and release_js.count("root.addEventListener('click'") == 1,
        'user javascript is preserved byte-for-byte': user_js in release_js,
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        for name in failed:
            print(f'web-bundle-hardening: FAIL: {name}')
        print(f'web-bundle-hardening: debug={len(debug_js)} release={len(release_js)} bytes')
        return 1

    checked = subprocess.run(['node', '--check', str(release_js_path)], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if checked.returncode != 0:
        print(checked.stdout)
        return 1

    print(f'web-bundle-hardening: PASS (generated loader {len(debug_js)} -> {len(release_js)} bytes; user JS preserved)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
