# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "passg_cycle_b"
version = "1.0.0"
kind = "static-library"
entry = "src/lib.rz"

[dependencies]
a = "../package-cycle-a"
