// Copyright 2026 Mario Vinciguerra
// SPDX-License-Identifier: Apache-2.0

std::string json_bool(bool value) { return value ? "true" : "false"; }

int coverage_project(const ProjectGraph& graph) {
  const auto root = graph.manifest.root / "target" / "coverage";
  std::filesystem::create_directories(root);
  std::string tests_text;
  const auto tests = graph.manifest.root / "tests";
  if (std::filesystem::is_directory(tests)) {
    for (const auto& entry : std::filesystem::recursive_directory_iterator(tests))
      if (entry.is_regular_file() && entry.path().extension() == ".rz") tests_text += read_text_file(entry.path()) + "\n";
  }

  struct Entry { std::string module, name, kind; std::size_t line; bool covered; };
  std::vector<Entry> entries;
  std::size_t covered = 0;
  for (const auto* module : project_modules(graph)) {
    for (const auto& symbol : lsp_symbols(read_text_file(module->source_path))) {
      const bool hit = tests_text.find(symbol.name) != std::string::npos;
      entries.push_back({module->logical_name, symbol.name, symbol.kind, symbol.line + 1, hit});
      if (hit) ++covered;
    }
  }
  std::ostringstream json;
  json << "{\n  \"schema\": \"raz-symbol-coverage-v1\",\n  \"package\": \"" << json_escape(graph.manifest.name)
       << "\",\n  \"covered\": " << covered << ",\n  \"total\": " << entries.size() << ",\n  \"symbols\": [\n";
  for (std::size_t i = 0; i < entries.size(); ++i) {
    const auto& e = entries[i];
    json << "    {\"module\":\"" << json_escape(e.module) << "\",\"name\":\"" << json_escape(e.name)
         << "\",\"kind\":\"" << e.kind << "\",\"line\":" << e.line << ",\"covered\":" << json_bool(e.covered) << "}";
    if (i + 1 != entries.size()) json << ',';
    json << '\n';
  }
  json << "  ]\n}\n";
  if (!write_text_file(root / "coverage.json", json.str())) return 1;
  std::ostringstream html;
  html << "<!doctype html><meta charset=\"utf-8\"><title>Raz coverage</title><h1>" << html_escape(graph.manifest.name)
       << " symbol coverage</h1><p>" << covered << " / " << entries.size() << " declarations referenced by tests.</p><table><tr><th>Module</th><th>Symbol</th><th>Kind</th><th>Status</th></tr>";
  for (const auto& e : entries) html << "<tr><td>" << html_escape(e.module) << "</td><td>" << html_escape(e.name)
      << "</td><td>" << e.kind << "</td><td>" << (e.covered ? "covered" : "uncovered") << "</td></tr>";
  html << "</table><p>This is deterministic symbol-reference coverage, not runtime line instrumentation.</p>";
  if (!write_text_file(root / "index.html", html.str())) return 1;
  std::cout << "Coverage: " << covered << '/' << entries.size() << " symbols referenced; report " << (root / "index.html") << '\n';
  return 0;
}

std::uint64_t fuzz_next(std::uint64_t& state) {
  state ^= state << 13; state ^= state >> 7; state ^= state << 17; return state;
}

int fuzz_project(const ProjectGraph& graph, const Options& options) {
  const auto root = graph.manifest.root / "target" / "fuzz";
  std::filesystem::remove_all(root);
  std::filesystem::create_directories(root);
  std::uint64_t state = options.seed ? options.seed : 1;
  unsigned accepted = 0;
  for (unsigned index = 0; index < options.cases; ++index) {
    const auto a = static_cast<std::int64_t>(fuzz_next(state) % 100000);
    const auto b = static_cast<std::int64_t>(fuzz_next(state) % 100000);
    const auto op = std::array<const char*, 4>{"+", "-", "*", "%"}[fuzz_next(state) % 4];
    const auto divisor = (op == std::string_view("%") && b == 0) ? 1 : b;
    std::ostringstream source;
    source << "fn fuzz_" << index << "() -> i64 {\n  i64 value = " << a << ' ' << op << ' ' << divisor << ";\n";
    if ((fuzz_next(state) & 1U) != 0) source << "  if value > 0 { value += 1; }\n";
    source << "  return value;\n}\nfn main() -> i64 { return fuzz_" << index << "(); }\n";
    const auto path = root / ("case-" + std::to_string(index) + ".rz");
    if (!write_text_file(path, source.str())) return 1;
    SessionOptions session; session.input = path; session.check_only = true;
    if (Compiler{}.run(Session(std::move(session))) != 0) {
      std::cerr << "raz fuzz: generated case rejected: " << path << " (seed " << options.seed << ")\n";
      return 1;
    }
    ++accepted;
  }
  std::ostringstream manifest;
  manifest << "seed=" << options.seed << "\ncases=" << accepted << "\nstatus=passed\n";
  write_text_file(root / "FUZZ-RESULT.txt", manifest.str());
  std::cout << "Fuzzed " << accepted << " deterministic compiler cases with seed " << options.seed << '\n';
  return 0;
}

std::string expected_lockfile(const ProjectGraph& graph) {
  std::vector<std::string> entries;
  collect_lock_entries(graph, graph.manifest.root, entries);
  std::sort(entries.begin(), entries.end());
  std::ostringstream output;
  output << "# Generated by Raz. Do not edit manually.\nversion = 1\n\n";
  for (const auto& entry : entries) output << entry << '\n';
  return output.str();
}

int generate_sbom(const ProjectGraph& graph, bool audit_only) {
  const auto root = graph.manifest.root / "target" / "security";
  std::filesystem::create_directories(root);
  std::vector<const ProjectGraph*> projects;
  std::function<void(const ProjectGraph&)> collect = [&](const ProjectGraph& node) {
    projects.push_back(&node);
    for (const auto& dep : node.dependencies) collect(dep);
  };
  collect(graph);
  bool ok = true;
  for (const auto* project : projects) {
    if (!std::filesystem::exists(project->manifest.root / "raz.toml")) {
      std::cerr << "audit[E001]: missing manifest for " << project->manifest.name << '\n'; ok = false;
    }

    for (const auto& module : project->modules) {
      if (!std::filesystem::exists(module.source_path)) {
        std::cerr << "audit[E002]: missing source " << module.source_path << '\n'; ok = false;
      }
      if (std::filesystem::is_symlink(module.source_path)) {
        std::cerr << "audit[E003]: source symlink is not package-safe: " << module.source_path << '\n'; ok = false;
      }
    }
  }

  if (!audit_only) {
    std::ostringstream json;
    json << "{\n  \"format\": \"raz-sbom-v1\",\n  \"root\": \"" << json_escape(graph.manifest.name) << "\",\n  \"packages\": [\n";
    for (std::size_t i = 0; i < projects.size(); ++i) {
      const auto& m = projects[i]->manifest;
      json << "    {\"name\":\"" << json_escape(m.name) << "\",\"version\":\"" << json_escape(m.version)
           << "\",\"kind\":\"" << raz::compiler::package_kind_name(m.kind) << "\",\"manifest_hash\":\""
           << hex(hash_file(m.root / "raz.toml", "raz-sbom-v1")) << "\"}" << (i + 1 == projects.size() ? "" : ",") << '\n';
    }
    json << "  ]\n}\n";
    if (!write_text_file(root / "sbom.json", json.str())) return 1;
    cli_status("Generated", std::string("SBOM at ") + (root / "sbom.json").string(), raz::terminal::green);
  }

  if (ok) std::cout << "Audit passed for " << projects.size() << " package(s)\n";
  return ok ? 0 : 1;
}

int verify_project(const ProjectGraph& graph) {
  const auto lock = graph.manifest.root / "raz.lock";
  if (!std::filesystem::exists(lock)) {
    std::cerr << "raz verify: missing raz.lock; run 'raz lock'\n";
    return 1;
  }

  if (read_text_file(lock) != expected_lockfile(graph)) {
    std::cerr << "raz verify: raz.lock is stale or modified\n";
    return 1;
  }
  std::size_t modules = 0;
  for (const auto* module : project_modules(graph)) {
    ++modules;
    if (!std::filesystem::exists(module->source_path)) {
      std::cerr << "raz verify: missing module " << module->source_path << '\n';
      return 1;
    }
    SessionOptions session;
    session.input = module->source_path;
    session.check_only = true;
    if (Compiler{}.run(Session(std::move(session))) != 0) return 1;
  }

  cli_status("Verified", graph.manifest.name + " (lockfile current, " + std::to_string(modules) + " module(s) valid)", raz::terminal::green);
  return 0;
}

int profile_project(const ProjectGraph& graph) {
  const auto root = graph.manifest.root / "target" / "profile";
  std::filesystem::create_directories(root);
  struct Result { std::string module; double milliseconds; int status; };
  std::vector<Result> results;
  double total = 0.0;
  for (const auto* module : project_modules(graph)) {
    SessionOptions session;
    session.input = module->source_path;
    session.check_only = true;
    const auto begin = std::chrono::steady_clock::now();
    const int status = Compiler{}.run(Session(std::move(session)));
    const auto end = std::chrono::steady_clock::now();
    const double elapsed = std::chrono::duration<double, std::milli>(end - begin).count();
    total += elapsed;
    results.push_back({module->logical_name, elapsed, status});
    if (status != 0) return 1;
  }

  std::sort(results.begin(), results.end(), [](const Result& a, const Result& b) {
    if (a.milliseconds != b.milliseconds) return a.milliseconds > b.milliseconds;
    return a.module < b.module;
  });
  std::ostringstream json;
  json << "{\n  \"schema\": \"raz-compile-profile-v1\",\n  \"package\": \"" << json_escape(graph.manifest.name)
       << "\",\n  \"total_ms\": " << std::fixed << std::setprecision(3) << total << ",\n  \"modules\": [\n";
  for (std::size_t i = 0; i < results.size(); ++i) {
    json << "    {\"module\":\"" << json_escape(results[i].module) << "\",\"check_ms\":"
         << std::fixed << std::setprecision(3) << results[i].milliseconds << "}";
    if (i + 1 != results.size()) json << ',';
    json << '\n';
  }
  json << "  ]\n}\n";
  if (!write_text_file(root / "compile-profile.json", json.str())) return 1;
  std::ostringstream text;
  text << "Raz compile profile for " << graph.manifest.name << "\n";
  for (const auto& result : results) text << std::fixed << std::setprecision(3) << result.milliseconds << " ms  " << result.module << '\n';
  text << std::fixed << std::setprecision(3) << total << " ms total\n";
  if (!write_text_file(root / "compile-profile.txt", text.str())) return 1;
  std::cout << "Profiled " << results.size() << " module(s) in " << std::fixed << std::setprecision(3) << total << " ms\n";
  return 0;
}

int emit_language_spec(const ProjectGraph& graph) {
  const auto output_root = graph.manifest.root / "target" / "spec";
  std::filesystem::create_directories(output_root);
  const auto source_root = std::filesystem::path(RAZ_SOURCE_ROOT);
  const std::array<std::pair<std::string_view, std::filesystem::path>, 4> documents{{
      {"language", source_root / "docs" / "LANGUAGE-SPECIFICATION.md"},
      {"stableScope", source_root / "docs" / "LANGUAGE-STABILITY.md"},
      {"architecture", source_root / "docs" / "ARCHITECTURE.md"},
      {"toolchain", source_root / "docs" / "TOOLCHAIN-SPECIFICATION.md"},
  }};
  std::ostringstream manifest;
  manifest << "{\n  \"schema\": \"raz-language-spec-v1\",\n"
           << "  \"languageVersion\": \"1.0\",\n"
           << "  \"package\": \"" << json_escape(graph.manifest.name) << "\",\n"
           << "  \"documents\": [\n";
  for (std::size_t i = 0; i < documents.size(); ++i) {
    const auto& [name, source] = documents[i];
    if (!std::filesystem::exists(source)) {
      std::cerr << "raz spec: missing specification document: " << source << '\n';
      return 1;
    }
    const auto destination = output_root / source.filename();
    std::filesystem::copy_file(source, destination, std::filesystem::copy_options::overwrite_existing);
    manifest << "    {\"name\":\"" << name << "\",\"file\":\""
             << json_escape(destination.filename().generic_string()) << "\",\"checksum\":\""
             << hex(hash_file(destination, "raz-spec-v1")) << "\"}";
    if (i + 1 != documents.size()) manifest << ',';
    manifest << '\n';
  }
  manifest << "  ]\n}\n";
  if (!write_text_file(output_root / "spec.json", manifest.str())) return 1;
  std::cout << "Emitted Raz 1.0 specification bundle at " << output_root << '\n';
  return 0;
}

int publish_project(const ProjectGraph& graph, Options options) {
  if (options.registry.empty()) options.registry = graph.manifest.root / "target" / "registry";
  if (package_project(graph, options) != 0) return 1;
  const auto archive = graph.manifest.root / "target" / "package" /
      (graph.manifest.name + "-" + graph.manifest.version + ".zip");
  if (!std::filesystem::exists(archive)) {
    std::cerr << "raz publish: package archive missing\n";
    return 1;
  }
  const auto destination = options.registry / graph.manifest.name / graph.manifest.version;
  std::filesystem::create_directories(destination);
  const auto published = destination / archive.filename();
  std::filesystem::copy_file(archive, published, std::filesystem::copy_options::overwrite_existing);
  std::ostringstream metadata;
  metadata << "{\n  \"schema\": \"raz-registry-package-v1\",\n  \"name\": \"" << json_escape(graph.manifest.name)
           << "\",\n  \"version\": \"" << json_escape(graph.manifest.version)
           << "\",\n  \"archive\": \"" << json_escape(published.filename().generic_string())
           << "\",\n  \"checksum\": \"" << hex(hash_file(published, "raz-publish-v1")) << "\"\n}\n";
  if (!write_text_file(destination / "package.json", metadata.str())) return 1;
  cli_status("Published", graph.manifest.name + " " + graph.manifest.version + " to " + destination.string(), raz::terminal::green);
  return 0;
}

int install_project(const ProjectGraph& graph, Options options, bool uninstall) {
  if (options.prefix.empty()) {
    const std::string home = environment_value("HOME");
    if (!home.empty()) options.prefix = std::filesystem::path(home) / ".raz";
#if defined(_WIN32)
    else {
      const std::string profile = environment_value("USERPROFILE");
      if (!profile.empty()) options.prefix = std::filesystem::path(profile) / ".raz";
      else options.prefix = graph.manifest.root / "target" / "install";
    }
#else
    else options.prefix = graph.manifest.root / "target" / "install";
#endif
  }
  const auto bin = options.prefix / "bin";
  const auto packages = options.prefix / "packages" / graph.manifest.name / graph.manifest.version;
  const auto artifact = native_artifact_path(graph, options);
  if (uninstall) {
    std::error_code error;
    std::filesystem::remove(bin / artifact.filename(), error);
    std::filesystem::remove_all(packages, error);
    std::cout << "Uninstalled " << graph.manifest.name << " from " << options.prefix << '\n';
    return 0;
  }
  options.profile = "release";
  std::set<std::filesystem::path> built;
  std::size_t compiled = 0, fresh = 0;
  if (!build_graph(graph, options, false, built, compiled, fresh)) return 1;
  const auto built_artifact = native_artifact_path(graph, options);
  if (!std::filesystem::exists(built_artifact)) { std::cerr << "raz install: native artifact missing\n"; return 1; }
  std::filesystem::create_directories(bin);
  std::filesystem::create_directories(packages);
  std::filesystem::copy_file(built_artifact, bin / built_artifact.filename(), std::filesystem::copy_options::overwrite_existing);
  std::filesystem::copy_file(graph.manifest.root / "raz.toml", packages / "raz.toml", std::filesystem::copy_options::overwrite_existing);
  if (std::filesystem::exists(graph.manifest.root / "raz.lock"))
    std::filesystem::copy_file(graph.manifest.root / "raz.lock", packages / "raz.lock", std::filesystem::copy_options::overwrite_existing);
  std::ofstream receipt(packages / "INSTALL-RECEIPT.txt", std::ios::trunc);
  receipt << "raz-install-v1\npackage=" << graph.manifest.name << "\nversion=" << graph.manifest.version
          << "\nartifact=" << (bin / built_artifact.filename()).generic_string() << '\n';
  cli_status("Installed", graph.manifest.name + " to " + options.prefix.string(), raz::terminal::green);
  return 0;
}

void lsp_send(std::string_view body) {
  std::cout << "Content-Length: " << body.size() << "\r\n\r\n" << body << std::flush;
}

int dependency_graph(const ProjectGraph& graph) {
  const auto output_root = graph.manifest.root / "target" / "metadata";
  std::filesystem::create_directories(output_root);
  const auto json_path = output_root / "dependency-graph.json";
  const auto dot_path = output_root / "dependency-graph.dot";
  std::vector<const ProjectGraph*> nodes;
  std::function<void(const ProjectGraph&)> collect = [&](const ProjectGraph& current) {
    nodes.push_back(&current);
    for (const auto& dependency : current.dependencies) collect(dependency);
  };
  collect(graph);
  std::sort(nodes.begin(), nodes.end(), [](const auto* lhs, const auto* rhs) {
    return lhs->manifest.name < rhs->manifest.name;
  });
  std::ofstream json(json_path, std::ios::trunc);
  json << "{\n  \"schema\": \"raz-dependency-graph-v1\",\n  \"root\": \"" << json_escape(graph.manifest.name) << "\",\n  \"packages\": [\n";
  for (std::size_t i = 0; i < nodes.size(); ++i) {
    const auto& node = *nodes[i];
    json << "    {\"name\":\"" << json_escape(node.manifest.name) << "\",\"version\":\""
         << json_escape(node.manifest.version) << "\",\"dependencies\":[";
    for (std::size_t j = 0; j < node.dependencies.size(); ++j) {
      if (j) json << ',';
      json << "\"" << json_escape(node.dependencies[j].manifest.name) << "\"";
    }
    json << "]}" << (i + 1 == nodes.size() ? "\n" : ",\n");
  }
  json << "  ]\n}\n";
  std::ofstream dot(dot_path, std::ios::trunc);
  dot << "digraph raz_dependencies {\n  rankdir=LR;\n";
  for (const auto* node : nodes) {
    dot << "  \"" << node->manifest.name << "\" [label=\"" << node->manifest.name << "\\n" << node->manifest.version << "\"];\n";
    for (const auto& dependency : node->dependencies)
      dot << "  \"" << node->manifest.name << "\" -> \"" << dependency.manifest.name << "\";\n";
  }
  dot << "}\n";
  cli_status("Generated", "dependency graph for " + std::to_string(nodes.size()) + " package(s) at " + output_root.string(), raz::terminal::green);
  return json && dot ? 0 : 1;
}

std::optional<std::filesystem::path> find_tool_on_path(std::string_view tool) {
  if (tool.empty()) return std::nullopt;
  const std::filesystem::path requested(tool);
  if (requested.has_parent_path()) {
    std::error_code error;
    if (std::filesystem::is_regular_file(requested, error)) return std::filesystem::absolute(requested, error);
    return std::nullopt;
  }

  const auto path_value = environment_value("PATH");
  if (path_value.empty()) return std::nullopt;
#if defined(_WIN32)
  constexpr char separator = ';';
  std::vector<std::string> suffixes{""};
  if (!requested.has_extension()) {
    const auto pathext = environment_value("PATHEXT");
    if (!pathext.empty()) {
      std::size_t begin = 0;
      while (begin <= pathext.size()) {
        const auto next = pathext.find(';', begin);
        auto suffix = pathext.substr(begin, next == std::string::npos ? std::string::npos : next - begin);
        std::transform(suffix.begin(), suffix.end(), suffix.begin(),
                       [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        if (!suffix.empty()) suffixes.push_back(std::move(suffix));
        if (next == std::string::npos) break;
        begin = next + 1;
      }
    } else {
      suffixes.insert(suffixes.end(), {".exe", ".cmd", ".bat"});
    }
  }
#else
  constexpr char separator = ':';
#endif

  std::size_t begin = 0;
  while (begin <= path_value.size()) {
    const auto next = path_value.find(separator, begin);
    auto directory = path_value.substr(begin, next == std::string::npos ? std::string::npos : next - begin);
    if (directory.empty()) directory = ".";
#if defined(_WIN32)
    for (const auto& suffix : suffixes) {
      std::filesystem::path candidate = std::filesystem::path(directory) / (std::string(tool) + suffix);
      std::error_code error;
      if (std::filesystem::is_regular_file(candidate, error)) return std::filesystem::absolute(candidate, error);
    }
#else
    std::filesystem::path candidate = std::filesystem::path(directory) / std::string(tool);
    std::error_code error;
    const auto status = std::filesystem::status(candidate, error);
    if (!error && std::filesystem::is_regular_file(status)) {
      const auto permissions = status.permissions();
      using P = std::filesystem::perms;
      if ((permissions & (P::owner_exec | P::group_exec | P::others_exec)) != P::none)
        return std::filesystem::absolute(candidate, error);
    }
#endif
    if (next == std::string::npos) break;
    begin = next + 1;
  }
  return std::nullopt;
}

int doctor_toolchain(const Options& options) {
  bool healthy = true;
  cli_status("Checking", "Raz toolchain and host environment", raz::terminal::cyan);
  cli_status("OK", "Raz 1.0.0", raz::terminal::green);

#if defined(_WIN32)
  constexpr std::string_view host_os = "windows";
#else
  constexpr std::string_view host_os = "posix";
#endif
#if defined(__x86_64__) || defined(_M_X64)
  constexpr std::string_view host_arch = "x86_64";
#elif defined(__aarch64__) || defined(_M_ARM64)
  constexpr std::string_view host_arch = "aarch64";
#else
  constexpr std::string_view host_arch = "unknown";
#endif
  cli_status("Host", std::string(host_os) + "-" + std::string(host_arch) + ", " +
      std::to_string(sizeof(void*) * 8U) + "-bit, " +
      std::to_string(std::max(1U, std::thread::hardware_concurrency())) + " hardware thread(s)",
      raz::terminal::cyan);
  if (host_arch == "unknown" || sizeof(void*) != 8) {
    cli_error("the bundled Forge backend requires a supported 64-bit host architecture");
    healthy = false;
  }

  const auto linker_name = native_linker();
  const auto linker_path = find_tool_on_path(linker_name);
  if (linker_path) {
    cli_status("Linker", linker_name + " -> " + linker_path->string(), raz::terminal::green);
  } else {
    cli_errorf("native linker driver not found: ", linker_name);
    cli_hint("install a compatible C++ linker driver or set RAZ_LINKER to its executable path");
    healthy = false;
  }

  if (!g_self_executable.empty()) {
    std::error_code executable_error;
    auto executable = std::filesystem::absolute(g_self_executable, executable_error);
    cli_status("Driver", executable_error ? g_self_executable.string() : executable.string(), raz::terminal::cyan);
  }

  ProjectGraph graph;
  ProjectError project_error;
  const bool has_project = raz::compiler::discover_project(options.project, graph, project_error);
  std::filesystem::path report_path;
  if (has_project) {
    const auto project_entry = graph.manifest.entry.is_absolute()
        ? graph.manifest.entry : graph.manifest.root / graph.manifest.entry;
    const bool entry_exists = std::filesystem::is_regular_file(project_entry);
    const bool has_modules = !graph.modules.empty();
    cli_status("Project", graph.manifest.name + " v" + graph.manifest.version + " (" +
        std::to_string(project_modules(graph).size()) + " module(s))",
        entry_exists && has_modules ? raz::terminal::green : raz::terminal::red);
    if (!entry_exists) { cli_errorf("project entry does not exist: ", project_entry); healthy = false; }
    if (!has_modules) { cli_error("project contains no compilable modules"); healthy = false; }

    const auto output_root = graph.manifest.root / "target" / "doctor";
    std::error_code directory_error;
    std::filesystem::create_directories(output_root, directory_error);
    if (!directory_error) report_path = output_root / "doctor.json";
  } else if (options.project_explicit) {
    cli_errorf("could not discover a Raz project from ", options.project, ": ", project_error.message);
    healthy = false;
  } else {
    cli_status("Project", "no package detected; toolchain-only checks completed", raz::terminal::yellow);
  }

  if (!report_path.empty()) {
    std::ofstream report(report_path, std::ios::trunc);
    report << "{\n  \"schema\": \"raz-doctor-v2\",\n"
           << "  \"healthy\": " << (healthy ? "true" : "false") << ",\n"
           << "  \"version\": \"1.0.0\",\n"
           << "  \"host\": \"" << host_os << '-' << host_arch << "\",\n"
           << "  \"pointerBits\": " << sizeof(void*) * 8U << ",\n"
           << "  \"hardwareThreads\": " << std::max(1U, std::thread::hardware_concurrency()) << ",\n"
           << "  \"linker\": \"" << json_escape(linker_name) << "\",\n"
           << "  \"linkerFound\": " << (linker_path ? "true" : "false") << ",\n"
           << "  \"package\": \"" << json_escape(graph.manifest.name) << "\",\n"
           << "  \"modules\": " << project_modules(graph).size() << "\n}\n";
    if (!report) { cli_errorf("could not write doctor report: ", report_path); healthy = false; }
    else cli_status("Report", report_path.string(), raz::terminal::cyan);
  }

  cli_status(healthy ? "Finished" : "Failed",
             healthy ? "toolchain is ready" : "toolchain has problems that require attention",
             healthy ? raz::terminal::green : raz::terminal::red);
  return healthy ? 0 : 1;
}

int cache_project(const ProjectGraph& graph, const Options& options) {
  const auto cache_root = graph.manifest.root / ".raz" / "cache";
  if (options.prune_cache) {
    std::error_code error;
    const auto removed = std::filesystem::remove_all(cache_root, error);
    if (error) { std::cerr << "raz cache: " << error.message() << '\n'; return 1; }
    std::cout << "Pruned " << removed << " cache entries\n";
    return 0;
  }
  std::uintmax_t bytes = 0; std::size_t files = 0;
  if (std::filesystem::exists(cache_root)) {
    for (const auto& entry : std::filesystem::recursive_directory_iterator(cache_root)) {
      if (!entry.is_regular_file()) continue;
      ++files; bytes += entry.file_size();
    }
  }
  std::cout << "Cache " << cache_root << ": " << files << " file(s), " << bytes << " byte(s)\n";
  return 0;
}
