# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED FORGE OR NOT EXISTS "${FORGE}")
  message(FATAL_ERROR "FORGE must point to the Forge CLI")
endif()
if(NOT DEFINED OBLINK OR NOT EXISTS "${OBLINK}")
  message(FATAL_ERROR "OBLINK must point to the ObLink CLI")
endif()
set(FIR "${CMAKE_CURRENT_BINARY_DIR}/oblink-forge-compat.fir")
set(OBJ "${CMAKE_CURRENT_BINARY_DIR}/oblink-forge-compat.obj")
set(EXE "${CMAKE_CURRENT_BINARY_DIR}/oblink-forge-compat.exe")
file(WRITE "${FIR}" "module @oblink_compat {\n  func @main() -> i64 {\n  entry:\n    %zero = const i64 0\n    return %zero\n  }\n}\n")
execute_process(COMMAND "${FORGE}" compile "${FIR}" --format=coff -o "${OBJ}" RESULT_VARIABLE forge_status)
if(NOT forge_status EQUAL 0)
  message(FATAL_ERROR "Forge COFF emission failed: ${forge_status}")
endif()
execute_process(COMMAND "${OBLINK}" "${OBJ}" -o "${EXE}" RESULT_VARIABLE link_status)
if(NOT link_status EQUAL 0 OR NOT EXISTS "${EXE}")
  message(FATAL_ERROR "ObLink Forge compatibility link failed: ${link_status}")
endif()
file(READ "${EXE}" magic OFFSET 0 LIMIT 2 HEX)
string(TOLOWER "${magic}" magic)
if(NOT magic STREQUAL "4d5a")
  message(FATAL_ERROR "ObLink output is not an MZ/PE image")
endif()
message(STATUS "Forge -> COFF -> ObLink -> PE compatibility PASS")
