# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED FORGE OR NOT EXISTS "${FORGE}")
  message(FATAL_ERROR "FORGE must point to the Forge CLI")
endif()
if(NOT DEFINED OBLINK OR NOT EXISTS "${OBLINK}")
  message(FATAL_ERROR "OBLINK must point to the ObLink CLI")
endif()
if(NOT DEFINED WORK_DIR)
  set(WORK_DIR "${CMAKE_CURRENT_BINARY_DIR}/oblink-forge-compat")
endif()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")
set(FIR "${WORK_DIR}/oblink-forge-compat.fir")
set(OBJ "${WORK_DIR}/oblink-forge-compat.obj")
set(EXE1 "${WORK_DIR}/oblink-forge-compat-a.exe")
set(EXE2 "${WORK_DIR}/oblink-forge-compat-b.exe")
file(WRITE "${FIR}" "module @oblink_compat {\n  func @main() -> i64 {\n  entry:\n    %zero = const i64 0\n    return %zero\n  }\n}\n")
execute_process(COMMAND "${FORGE}" compile "${FIR}" --format=coff -o "${OBJ}" RESULT_VARIABLE forge_status OUTPUT_VARIABLE forge_output ERROR_VARIABLE forge_error)
if(NOT forge_status EQUAL 0)
  message(FATAL_ERROR "Forge COFF emission failed: ${forge_status}\n${forge_output}\n${forge_error}")
endif()
foreach(exe IN ITEMS "${EXE1}" "${EXE2}")
  execute_process(COMMAND "${OBLINK}" "${OBJ}" -o "${exe}" RESULT_VARIABLE link_status OUTPUT_VARIABLE link_output ERROR_VARIABLE link_error)
  if(NOT link_status EQUAL 0 OR NOT EXISTS "${exe}")
    message(FATAL_ERROR "ObLink Forge compatibility link failed: ${link_status}\n${link_output}\n${link_error}")
  endif()
  file(READ "${exe}" magic OFFSET 0 LIMIT 2 HEX)
  string(TOLOWER "${magic}" magic)
  if(NOT magic STREQUAL "4d5a")
    message(FATAL_ERROR "ObLink output is not an MZ/PE image")
  endif()
endforeach()
file(SHA256 "${EXE1}" sha1)
file(SHA256 "${EXE2}" sha2)
if(NOT sha1 STREQUAL sha2)
  message(FATAL_ERROR "Forge -> ObLink output is not deterministic: ${sha1} != ${sha2}")
endif()
message(STATUS "Forge -> COFF -> ObLink -> deterministic PE compatibility PASS (${sha1})")
