# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "raz-compiler"
version = "1.0.0"
kind = "executable"
source = "src"
entry = "src/main.rz"

[dependencies]
driver = "src/raz_driver"

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 2
debug = false
incremental = true
