# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
string(REGEX MATCH "short-branches=([0-9]+)" _branch_match "${output}")
set(short_branches "${CMAKE_MATCH_1}")
string(REGEX MATCH "forward-short-branches=([0-9]+)" _forward_match "${output}")
set(forward_short_branches "${CMAKE_MATCH_1}")
string(REGEX MATCH "short-branch-bytes-avoided=([0-9]+)" _avoided_match "${output}")
set(bytes_avoided "${CMAKE_MATCH_1}")
string(REGEX MATCH "fallthrough-jumps-removed=([0-9]+)" _fallthrough_match "${output}")
set(fallthrough_jumps "${CMAKE_MATCH_1}")
string(REGEX MATCH "layout-bytes-avoided=([0-9]+)" _layout_match "${output}")
set(layout_bytes "${CMAKE_MATCH_1}")
string(REGEX MATCH "bytes=([0-9]+)" _bytes_match "${output}")
set(encoded_bytes "${CMAKE_MATCH_1}")
if(short_branches STREQUAL "" OR forward_short_branches STREQUAL "" OR bytes_avoided STREQUAL "" OR fallthrough_jumps STREQUAL "" OR layout_bytes STREQUAL "" OR encoded_bytes STREQUAL "")
 message(FATAL_ERROR "unable to parse short-branch statistics: ${output}")
endif()
if(short_branches LESS MIN_SHORT_BRANCHES)
 message(FATAL_ERROR "short-branch regression: ${short_branches} < ${MIN_SHORT_BRANCHES}")
endif()
if(forward_short_branches LESS MIN_FORWARD_SHORT_BRANCHES)
 message(FATAL_ERROR "forward short-branch regression: ${forward_short_branches} < ${MIN_FORWARD_SHORT_BRANCHES}")
endif()
if(bytes_avoided LESS MIN_BYTES_AVOIDED)
 message(FATAL_ERROR "short-branch byte regression: ${bytes_avoided} < ${MIN_BYTES_AVOIDED}")
endif()
if(fallthrough_jumps LESS MIN_FALLTHROUGH_JUMPS)
 message(FATAL_ERROR "fallthrough jump regression: ${fallthrough_jumps} < ${MIN_FALLTHROUGH_JUMPS}")
endif()
if(layout_bytes LESS MIN_LAYOUT_BYTES_AVOIDED)
 message(FATAL_ERROR "layout byte regression: ${layout_bytes} < ${MIN_LAYOUT_BYTES_AVOIDED}")
endif()
if(encoded_bytes GREATER MAX_ENCODED_BYTES)
 message(FATAL_ERROR "short-branch encoded-byte regression: ${encoded_bytes} > ${MAX_ENCODED_BYTES}")
endif()
message(STATUS "Forge branch layout: short=${short_branches}, fallthrough=${fallthrough_jumps}, branch-bytes=${bytes_avoided}, layout-bytes=${layout_bytes}, bytes=${encoded_bytes}/${MAX_ENCODED_BYTES}")
