# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(
 COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats
 RESULT_VARIABLE result
 OUTPUT_VARIABLE output
 ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
string(REGEX MATCH "instructions=([0-9]+)" _after_match "${output}")
set(instructions_after "${CMAKE_MATCH_1}")
string(REGEX MATCH "instructions-before-machine-opt=([0-9]+)" _before_match "${output}")
set(instructions_before "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-instructions-eliminated=([0-9]+)" _removed_match "${output}")
set(instructions_removed "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-copies-propagated=([0-9]+)" _copies_match "${output}")
set(copies_propagated "${CMAKE_MATCH_1}")
string(REGEX MATCH "leaf-frames-elided=([0-9]+)" _leaf_match "${output}")
set(leaf_frames_elided "${CMAKE_MATCH_1}")
string(REGEX MATCH "leaf-frame-bytes-avoided=([0-9]+)" _leaf_bytes_match "${output}")
set(leaf_frame_bytes_avoided "${CMAKE_MATCH_1}")
string(REGEX MATCH "bytes=([0-9]+)" _bytes_match "${output}")
set(encoded_bytes "${CMAKE_MATCH_1}")
if(instructions_after STREQUAL "" OR instructions_before STREQUAL "" OR instructions_removed STREQUAL "" OR copies_propagated STREQUAL "" OR leaf_frames_elided STREQUAL "" OR leaf_frame_bytes_avoided STREQUAL "" OR encoded_bytes STREQUAL "")
 message(FATAL_ERROR "unable to parse machine-cleanup statistics: ${output}")
endif()
math(EXPR expected_removed "${instructions_before} - ${instructions_after}")
if(NOT instructions_removed EQUAL expected_removed)
 message(FATAL_ERROR "machine instruction accounting mismatch: ${instructions_removed} != ${expected_removed}")
endif()
if(copies_propagated LESS MIN_COPIES_PROPAGATED)
 message(FATAL_ERROR "machine copy propagation regression: ${copies_propagated} < ${MIN_COPIES_PROPAGATED}")
endif()
if(instructions_removed LESS MIN_INSTRUCTIONS_ELIMINATED)
 message(FATAL_ERROR "machine cleanup regression: ${instructions_removed} < ${MIN_INSTRUCTIONS_ELIMINATED}")
endif()
if(leaf_frames_elided LESS MIN_LEAF_FRAMES_ELIDED)
 message(FATAL_ERROR "leaf-frame elision regression: ${leaf_frames_elided} < ${MIN_LEAF_FRAMES_ELIDED}")
endif()
if(leaf_frame_bytes_avoided LESS MIN_LEAF_FRAME_BYTES_AVOIDED)
 message(FATAL_ERROR "leaf-frame byte regression: ${leaf_frame_bytes_avoided} < ${MIN_LEAF_FRAME_BYTES_AVOIDED}")
endif()
if(encoded_bytes GREATER MAX_ENCODED_BYTES)
 message(FATAL_ERROR "machine cleanup byte regression: ${encoded_bytes} > ${MAX_ENCODED_BYTES}")
endif()
message(STATUS "Forge machine cleanup: instructions=${instructions_after}/${instructions_before}, removed=${instructions_removed}, copies=${copies_propagated}, leaf=${leaf_frames_elided}, leaf-bytes=${leaf_frame_bytes_avoided}, bytes=${encoded_bytes}/${MAX_ENCODED_BYTES}")
