# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
foreach(metric machine-jump-threads machine-empty-blocks-removed machine-unreachable-blocks-removed machine-instructions-eliminated bytes)
 string(REPLACE "-" "_" variable "${metric}")
 string(REGEX MATCH "${metric}=([0-9]+)" _match "${output}")
 set(${variable} "${CMAKE_MATCH_1}")
 if(${variable} STREQUAL "")
  message(FATAL_ERROR "unable to parse ${metric}: ${output}")
 endif()
endforeach()
if(machine_jump_threads LESS MIN_JUMP_THREADS)
 message(FATAL_ERROR "jump-threading regression: ${machine_jump_threads} < ${MIN_JUMP_THREADS}")
endif()
if(machine_empty_blocks_removed LESS MIN_EMPTY_BLOCKS_REMOVED)
 message(FATAL_ERROR "empty-block regression: ${machine_empty_blocks_removed} < ${MIN_EMPTY_BLOCKS_REMOVED}")
endif()
if(machine_unreachable_blocks_removed LESS MIN_UNREACHABLE_BLOCKS_REMOVED)
 message(FATAL_ERROR "unreachable-block regression: ${machine_unreachable_blocks_removed} < ${MIN_UNREACHABLE_BLOCKS_REMOVED}")
endif()
if(machine_instructions_eliminated LESS MIN_INSTRUCTIONS_ELIMINATED)
 message(FATAL_ERROR "CFG instruction regression: ${machine_instructions_eliminated} < ${MIN_INSTRUCTIONS_ELIMINATED}")
endif()
if(bytes GREATER MAX_ENCODED_BYTES)
 message(FATAL_ERROR "CFG encoded-byte regression: ${bytes} > ${MAX_ENCODED_BYTES}")
endif()
message(STATUS "Forge CFG cleanup: threads=${machine_jump_threads}, empty=${machine_empty_blocks_removed}, unreachable=${machine_unreachable_blocks_removed}, eliminated=${machine_instructions_eliminated}, bytes=${bytes}/${MAX_ENCODED_BYTES}")
