# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(
 COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats
 RESULT_VARIABLE result
 OUTPUT_VARIABLE output
 ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
string(REGEX MATCH "instructions=([0-9]+)" _after_match "${output}")
set(instructions_after "${CMAKE_MATCH_1}")
string(REGEX MATCH "instructions-before-machine-opt=([0-9]+)" _before_match "${output}")
set(instructions_before "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-compare-branches-fused=([0-9]+)" _fused_match "${output}")
set(compare_branches_fused "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-compare-branch-bytes-avoided=([0-9]+)" _avoided_match "${output}")
set(bytes_avoided "${CMAKE_MATCH_1}")
string(REGEX MATCH "short-conditional-branches=([0-9]+)" _short_conditional_match "${output}")
set(short_conditional_branches "${CMAKE_MATCH_1}")
string(REGEX MATCH "short-conditional-branch-bytes-avoided=([0-9]+)" _short_conditional_bytes_match "${output}")
set(short_conditional_bytes_avoided "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-blocks-reordered=([0-9]+)" _reordered_match "${output}")
set(blocks_reordered "${CMAKE_MATCH_1}")
string(REGEX MATCH "fallthrough-jumps-removed=([0-9]+)" _fallthrough_match "${output}")
set(fallthrough_jumps "${CMAKE_MATCH_1}")
string(REGEX MATCH "branches-inverted=([0-9]+)" _inverted_match "${output}")
set(branches_inverted "${CMAKE_MATCH_1}")
string(REGEX MATCH "layout-bytes-avoided=([0-9]+)" _layout_match "${output}")
set(layout_bytes "${CMAKE_MATCH_1}")
string(REGEX MATCH "bytes=([0-9]+)" _bytes_match "${output}")
set(encoded_bytes "${CMAKE_MATCH_1}")
if(instructions_after STREQUAL "" OR instructions_before STREQUAL "" OR compare_branches_fused STREQUAL "" OR bytes_avoided STREQUAL "" OR short_conditional_branches STREQUAL "" OR short_conditional_bytes_avoided STREQUAL "" OR blocks_reordered STREQUAL "" OR fallthrough_jumps STREQUAL "" OR branches_inverted STREQUAL "" OR layout_bytes STREQUAL "" OR encoded_bytes STREQUAL "")
 message(FATAL_ERROR "unable to parse compare/branch statistics: ${output}")
endif()
if(compare_branches_fused LESS MIN_COMPARE_BRANCHES_FUSED)
 message(FATAL_ERROR "compare/branch fusion regression: ${compare_branches_fused} < ${MIN_COMPARE_BRANCHES_FUSED}")
endif()
if(bytes_avoided LESS MIN_FIXED_BYTES_AVOIDED)
 message(FATAL_ERROR "compare/branch byte regression: ${bytes_avoided} < ${MIN_FIXED_BYTES_AVOIDED}")
endif()
if(short_conditional_branches LESS MIN_SHORT_CONDITIONAL_BRANCHES)
 message(FATAL_ERROR "conditional short-branch regression: ${short_conditional_branches} < ${MIN_SHORT_CONDITIONAL_BRANCHES}")
endif()
if(short_conditional_bytes_avoided LESS MIN_SHORT_CONDITIONAL_BYTES_AVOIDED)
 message(FATAL_ERROR "conditional short-branch byte regression: ${short_conditional_bytes_avoided} < ${MIN_SHORT_CONDITIONAL_BYTES_AVOIDED}")
endif()
if(NOT instructions_before EQUAL 6 OR NOT instructions_after EQUAL 5)
 message(FATAL_ERROR "compare/branch instruction regression: ${instructions_after}/${instructions_before} != 5/6")
endif()
if(blocks_reordered LESS MIN_BLOCKS_REORDERED)
 message(FATAL_ERROR "block-layout regression: ${blocks_reordered} < ${MIN_BLOCKS_REORDERED}")
endif()
if(fallthrough_jumps LESS MIN_FALLTHROUGH_JUMPS)
 message(FATAL_ERROR "fallthrough regression: ${fallthrough_jumps} < ${MIN_FALLTHROUGH_JUMPS}")
endif()
if(branches_inverted LESS MIN_BRANCHES_INVERTED)
 message(FATAL_ERROR "branch-inversion regression: ${branches_inverted} < ${MIN_BRANCHES_INVERTED}")
endif()
if(layout_bytes LESS MIN_LAYOUT_BYTES_AVOIDED)
 message(FATAL_ERROR "layout byte regression: ${layout_bytes} < ${MIN_LAYOUT_BYTES_AVOIDED}")
endif()
if(encoded_bytes GREATER MAX_ENCODED_BYTES)
 message(FATAL_ERROR "compare/branch encoded-byte regression: ${encoded_bytes} > ${MAX_ENCODED_BYTES}")
endif()
message(STATUS "Forge compare/branch layout: instructions=${instructions_after}/${instructions_before}, fused=${compare_branches_fused}, reordered=${blocks_reordered}, fallthrough=${fallthrough_jumps}, inverted=${branches_inverted}, layout-bytes=${layout_bytes}, bytes=${encoded_bytes}/${MAX_ENCODED_BYTES}")
