# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
string(REGEX MATCH "instructions=([0-9]+)" _a "${output}")
set(after "${CMAKE_MATCH_1}")
string(REGEX MATCH "instructions-before-machine-opt=([0-9]+)" _b "${output}")
set(before "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-load-arithmetic-folded=([0-9]+)" _f "${output}")
set(folded "${CMAKE_MATCH_1}")
string(REGEX MATCH "bytes=([0-9]+)" _z "${output}")
set(bytes "${CMAKE_MATCH_1}")
if(folded LESS 1)
 message(FATAL_ERROR "memory arithmetic folding regression: ${output}")
endif()
if(NOT after LESS before)
 message(FATAL_ERROR "memory arithmetic did not remove an instruction: ${output}")
endif()
if(bytes GREATER 51)
 message(FATAL_ERROR "memory arithmetic byte regression: ${bytes} > 51")
endif()
message(STATUS "Forge memory arithmetic: instructions=${after}/${before}, folded=${folded}, bytes=${bytes}/51")
