# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

execute_process(COMMAND "${FORGE_CODEGEN}" "${INPUT}" --stats RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "forge-codegen failed: ${error}")
endif()
string(REGEX MATCH "machine-floating-compare-branches-fused=([0-9]+)" _fused "${output}")
set(fused "${CMAKE_MATCH_1}")
string(REGEX MATCH "machine-floating-compare-branch-bytes-avoided=([0-9]+)" _avoided "${output}")
set(avoided "${CMAKE_MATCH_1}")
string(REGEX MATCH "bytes=([0-9]+)" _bytes "${output}")
set(bytes "${CMAKE_MATCH_1}")
if(fused STREQUAL "" OR avoided STREQUAL "" OR bytes STREQUAL "")
 message(FATAL_ERROR "unable to parse floating comparison statistics: ${output}")
endif()
if(fused LESS MIN_FUSED)
 message(FATAL_ERROR "floating compare/branch fusion regression: ${fused} < ${MIN_FUSED}")
endif()
if(avoided LESS MIN_BYTES_AVOIDED)
 message(FATAL_ERROR "floating compare/branch byte regression: ${avoided} < ${MIN_BYTES_AVOIDED}")
endif()
if(bytes GREATER MAX_ENCODED_BYTES)
 message(FATAL_ERROR "floating compare encoded-byte regression: ${bytes} > ${MAX_ENCODED_BYTES}")
endif()
message(STATUS "Forge floating comparison quality: fused=${fused}, avoided=${avoided}, bytes=${bytes}/${MAX_ENCODED_BYTES}")
