# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

[package]
name = "raz-hir"
version = "1.0.0"
kind = "static-library"
source = "src"
entry = "src/lib.rz"

[dependencies]
querydb = "../raz_query"
frontend = "../raz_parser"

[profile.debug]
optimization = 0
debug = true
incremental = true

[profile.release]
optimization = 2
debug = false
incremental = true
