#!/usr/bin/env python3
# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
isa = (root / 'compiler/src/raz_codegen_rxe/src/rxe/isa.rz').read_text(encoding='utf-8')
writer = (root / 'compiler/src/raz_codegen_rxe/src/rxe/writer.rz').read_text(encoding='utf-8')
fmt = int(re.search(r'rxe_format_version\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}', isa).group(1))
isa_version = int(re.search(r'rxe_isa_version\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}', isa).group(1))
header = int(re.search(r'i64 header_bytes = (\d+);', writer).group(1))
ops = []
for name, value in re.findall(r'fn\s+rxe_op_([a-z0-9_]+)\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}', isa):
    ops.append((int(value), name.replace('_', '.')))
ops.sort()

text = [
    '# RXE ISA v1 / Binary Format Reference', '',
    '> Generated by `tools/generate-rxe-spec.py` from the Raz RXE implementation. Do not edit opcode numbers by hand.', '',
    f'- RXE container format: **v{fmt}**',
    f'- RXE instruction ISA: **v{isa_version}**',
    f'- Header size: **{header} bytes**',
    '- Architectural registers: **32**',
    '- Canonical instruction size: **8 bytes** (`opcode:u8 dst:u8 src0:u8 src1:u8 imm:u32`, little-endian)', '',
    '## v7 header', '',
    '| Offset | Field | Type |', '|---:|---|---|',
]
fields = [
    (0,'magic `RXE\\0`','u8[4]'),(4,'format_version','u16'),(6,'isa_version','u16'),
    (8,'feature_flags','u32'),(12,'function_count','u32'),(16,'instruction_count','u32'),
    (20,'constant_count','u32'),(24,'global_count','u32'),(28,'header_bytes','u32'),
    (32,'code_offset','u32'),(36,'code_bytes','u32'),(40,'constant_offset','u32'),
    (44,'constant_bytes','u32'),(48,'global_offset','u32'),(52,'global_bytes','u32'),
    (56,'layout_offset','u32'),(60,'layout_bytes','u32'),(64,'signature_offset','u32'),
    (68,'signature_bytes','u32'),(72,'function_type_count','u32'),(76,'signature_parameter_count','u32'),
    (80,'function_type_parameter_count','u32'),(84,'fingerprint_lo','u32'),(88,'fingerprint_hi','u32'),
    (92,'export_count','u32'),(96,'layout_count','u32'),(100,'layout_field_count','u32'),
]
for off,name,typ in fields:
    text.append(f'| {off} | `{name}` | `{typ}` |')
text += ['', 'The v7 addition at offsets 96 and 100 makes the aggregate-layout section independently decodable. v6 exposed only the combined byte size, which was insufficient to split layout and field records without compiler-side type information.', '', '## Section order', '', '```text', 'header', 'function directory', 'code', 'constant pool', 'global image', 'aggregate layouts', 'callable signatures', 'exports', 'basic-block directory', '```', '', '## Canonical opcodes', '', '| Opcode | Mnemonic |', '|---:|---|']
for value,name in ops:
    text.append(f'| {value} | `{name}` |')
text += ['', '## Compatibility invariant', '', 'Every emitted RXE file is read back by the Raz-side independent binary decoder. Section geometry and canonical reserved fields are validated, the image is re-encoded, and the result must be byte-identical before emission succeeds.', '']
(root / 'docs/RXE-v1-FORMAT.md').write_text('\n'.join(text), encoding='utf-8')
print(f'generated docs/RXE-v1-FORMAT.md (format v{fmt}, ISA v{isa_version}, {len(ops)} opcodes)')
