#!/usr/bin/env python3
# Copyright 2026 Mario Vinciguerra
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
import re, hashlib
root=Path(__file__).resolve().parents[1]
isa=(root/'compiler/src/backend/rxe/isa.rz').read_text(encoding='utf-8')
decoder=(root/'compiler/src/backend/rxe/decoder.rz').read_text(encoding='utf-8')
fmt=re.search(r'rxe_format_version\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}',isa).group(1)
ver=re.search(r'rxe_isa_version\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}',isa).group(1)
regs=re.search(r'rxe_register_count\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}',isa).group(1)
ops=[(name,int(num)) for name,num in re.findall(r'fn\s+rxe_op_([a-z0-9_]+)\(\)\s*->\s*i64\s*\{\s*return\s+(\d+);\s*\}',isa)]
sem={
'nop':'No observable effect.','movi':'dst = zero-extended imm32.','ldc64':'dst = constant[imm].','mov':'dst = src0.','load_arg':'dst = current-call argument[imm].','load_slot':'dst = frame slot[imm].','store_slot':'frame slot[imm] = dst.','load_local':'dst = local slot[imm].','store_local':'local slot[imm] = dst.','load_global':'dst = global[imm].','store_global':'global[imm] = dst.','global_ref':'dst = validated reference to global[imm].','local_ref':'dst = validated reference to local/frame storage selected by imm.','load_ref':'dst = value at validated reference src0.','store_ref':'value at validated reference dst = src0.','func_ref':'dst = canonical function handle for function imm.','jmp':'Transfer control to instruction imm within the current function.','brnz':'If dst != 0 branch to imm; otherwise fall through.','ret':'Return dst to caller.','ret_void':'Return without a value.','trap':'Terminate execution with a deterministic trap.','call':'Invoke direct function imm using staged ARG values; result in dst.','arg':'Stage dst as call argument index imm.','call_indirect':'Invoke function handle src0 using signature imm and staged arguments.','make_closure':'Create closure for function imm with staged captures; handle in dst.','call_closure':'Invoke closure handle src0 using signature imm and staged arguments.','add64':'dst = src0 + src1 modulo 2^64.','sub64':'dst = src0 - src1 modulo 2^64.','mul64':'dst = low 64 bits of src0 * src1.','div64':'Unsigned 64-bit division; divisor zero traps.','rem64':'Unsigned 64-bit remainder; divisor zero traps.','and64':'Bitwise AND.','or64':'Bitwise OR.','xor64':'Bitwise XOR.','shl64':'Logical left shift by src1 & 63.','shr64':'Logical unsigned right shift by src1 & 63.','divs64':'Signed two-complement division; zero and MIN/-1 trap.','rems64':'Signed two-complement remainder; zero and MIN/-1 trap.','sar64':'Arithmetic signed right shift by src1 & 63.','eq64':'dst = 1 iff src0 == src1, else 0.','ne64':'dst = 1 iff src0 != src1, else 0.','lt64':'Unsigned src0 < src1.','le64':'Unsigned src0 <= src1.','gt64':'Unsigned src0 > src1.','ge64':'Unsigned src0 >= src1.','select':'dst = src0 when selector register encoded by imm is nonzero, else src1.','not_bool':'dst = 1 iff src0 == 0, else 0.','trunc8':'Keep low 8 bits of src0.','trunc16':'Keep low 16 bits of src0.','trunc32':'Keep low 32 bits of src0.','sext8':'Sign-extend low 8 bits of src0 to 64 bits.','sext16':'Sign-extend low 16 bits of src0 to 64 bits.','sext32':'Sign-extend low 32 bits of src0 to 64 bits.','boolize':'dst = 0 if src0 == 0 else 1.','lts64':'Signed src0 < src1.','les64':'Signed src0 <= src1.','gts64':'Signed src0 > src1.','ges64':'Signed src0 >= src1.','alloc':'Allocate deterministic slot image described by imm; validated handle in dst.','free':'Invalidate the allocation referenced by dst; invalid/double/interior free traps.','index_load':'Bounds-checked load from src0[index=src1] into dst.','index_store':'Bounds-checked store to src0[index=src1] from register encoded by imm.','index_ref':'Create bounds-checked interior reference src0[index=src1] in dst.','string_ref':'dst = validated reference to canonical string/global image imm.','mem_copy':'Overlap-safe slot memmove from src0 to dst for imm slots; full ranges checked before mutation.','slice_load':'Bounds-check slice src0 using index src1 and load element into dst.','slice_store':'Bounds-check slice src0 using index src1 and store register encoded by imm.','slice_ref':'Bounds-check slice src0 using index src1 and produce element reference in dst.'}
missing=[n for n,_ in ops if n not in sem]
if missing: raise SystemExit(f'missing semantics: {missing}')
canon='\n'.join(f'{num}:{name}:{sem[name]}' for name,num in sorted(ops,key=lambda x:x[1]))
compatibility_hash=hashlib.sha256((f'isa={ver}\nformat={fmt}\nregisters={regs}\n'+canon).encode()).hexdigest()
lines=[
'# RXE ISA v1 Compatibility Manifest','',
'> Generated by `tools/generate-rxe-reference.py` from the RXE ISA plus the stable semantic descriptions in that generator. Do not edit by hand.','',
f'- RXE ISA: **v{ver}**',f'- RXE container format: **v{fmt}**',f'- Architectural registers: **{regs}**',f'- Canonical instruction width: **8 bytes** (`opcode:u8 dst:u8 src0:u8 src1:u8 imm:u32`, little-endian)',f'- Compatibility manifest SHA-256: `{compatibility_hash}`','',
'## Consensus-visible invariants','',
'- All arithmetic uses two-complement 64-bit register values; wrap/trap behavior is instruction-specific below.',
'- Branch targets are canonical instruction indices inside the current function.',
'- References are VM handles/offset identities, never host pointers.',
'- Invalid references, bounds violations, invalid calls, explicit `trap`, and specified arithmetic faults fail deterministically.',
'- `MEM_COPY` is overlap-safe and validates the complete source and destination ranges before mutation.',
'- Slice operations validate the slice length before resolving the element reference.',
'- RXE feature bits must equal the exact union required by the final opcode stream.',
'- Callable selectors are recomputed from name hash + ABI + complete parameter/return metadata; selector collisions are invalid.',
'- Export records must match their target callable descriptors and remain canonically selector-sorted.',
'- Canonical basic-block metadata must exactly partition functions and contain only in-function successors.',
'- Serialized RXE must pass independent decode + semantic validation + byte-identical re-encode.',
'', '## Stable opcode semantics','',
'| Opcode | Mnemonic | Stable behavior |','|---:|---|---|']
for name,num in sorted(ops,key=lambda x:x[1]):
    lines.append(f'| {num} | `{name.replace("_", ".")}` | {sem[name]} |')
lines += ['', '## Decoder trust boundary','',
'The independent Raz decoder must validate, from serialized bytes alone: section geometry, canonical reserved fields, opcode/register validity, exact feature bitmap, aggregate-layout ranges, signature ranges, recomputed callable selectors, export identity/order, and block partition/successor legality. The production C loader must implement the same consensus-visible checks independently.','',
'## Version rule','',
'Changing any opcode behavior above requires a new **RXE ISA version**. Changing only the self-describing container layout requires a new **RXE format version**. Compiler optimization and decoded µop/superinstruction changes do not change ISA version when canonical RXE behavior remains identical.','']
(root/'docs/RXE-ISA-v1.md').write_text('\n'.join(lines), encoding='utf-8')
print(f'generated RXE ISA v{ver} compatibility manifest ({len(ops)} opcodes) {compatibility_hash[:16]}')
